# Generated by Django 3.1.2 on 2020-10-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20201021_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('DEF', ''), ('ET', 'Entertainment'), ('TR', 'Travel'), ('FD', 'Food')], default='DEF', max_length=255),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('DEF', ''), ('DFT', 'Draft'), ('SUB', 'Submitted'), ('DEC', 'Declined'), ('PUB', 'Published')], default='DEF', max_length=255),
        ),
    ]
